apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "block-sensitive-keys-in-codebases"
spec:
  podSelector:
    matchLabels:
      app: build-code
  kprobes:
  - call: "security_file_open"
    syscall: false
    args:
    - index: 0
      type: "file"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Postfix"
        values:
        - ".git/config"
        - ".git/HEAD"
        - ".git/index"
        - ".env"
      matchActions:
      - action: Sigkill