apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: "block-dind-containerd-exploit"
spec:
  podSelector:
    matchLabels:
      app: health-check
  kprobes:

  # Block execution of crictl binary
  - call: "sys_execve"
    syscall: true
    args:
    - index: 0
      type: "string"
    selectors:
    - matchArgs:
      - index: 0
        operator: "Postfix"
        values:
        - "crictl"
      matchActions:
      - action: Sigkill