apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: "detect-ssrf-connect"
spec:
  podSelector:
    matchLabels:
      app: internal-proxy
  kprobes:
  - call: "tcp_connect"
    syscall: false
    args:
    - index: 0
      type: "sock"
    selectors:
    - matchArgs:
      - index: 0
        operator: "DAddr"
        # Check/replace values with metadata-db clusterIP
        # > kubectl get svc metadata-db
        values:
        - "10.103.191.164" 
      matchActions:
      - action: Sigkill